const mongoose=require('mongoose')

const visitorSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    aadhaar:{
        type:String
    },
    phone:{
        type:String
    },
    othernumber:{
        type:Number
    },
    gender:{
        type:String,
        required:true
    },
    category:{
        type:String,
        required:true
    },
    age:{
        type:Number,
        required:true
    },
    purposeVisit:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    }, 
    arrivedtime:{
        type:String,
        required:true
    },
    despachtime:{
        type:String
    },
    currentdate:{
        type:String,
        required:true
    },
    support:{
        type:String,
        required:true
    },
    image:{
        type:String
    },
    
    numberofstay:{
        type:String
    },
    
    attender:{
        type:String,
        required:true
    },
    status:{
        type:String,
        required:true
    },
    remarks:{
        type:String,
        required:true
    },
    userId:{
        type:String,
        required:true
    }
})

const visitors=mongoose.model('visitors',visitorSchema)
module.exports=visitors